const routes = {
   home: '/',
   order: '/order',
   myOrder: '/my-order',
   detailsOrder: '/details-order/:id',
   payment: '/payment',
   products: '/product',
   productType: '/product/:type',
   signIn: '/sign-in',
   signUp: '/sign-up',
   // ProductDetails: '/product-detail',
   ProductDetails: '/product-details/:id',
   profileUser: '/profile-user/:slug',
   Payment:'/payment',
   OrderSucess:'/orderSuccess',
   admin: localStorage.getItem('role') === 'admin' ? '/system/admin' : null,
   adminCreateUser:localStorage.getItem('role') === 'admin' ?'/system/admin/create': null,
   adminUpdateUser:localStorage.getItem('role') === 'admin' ?'/system/admin/update/:id': null,
   seller:localStorage.getItem('role') === 'seller' || localStorage.getItem('role') === 'ceo'  ?'/system/seller/:feature': null,
   sellerAdjustCreate:localStorage.getItem('role') === 'seller' || localStorage.getItem('role') === 'ceo' ?'/system/seller/:feature/:adjust': null,
   sellerAdjustUpdate:localStorage.getItem('role') === 'seller' || localStorage.getItem('role') === 'ceo' ?'/system/seller/:feature/:adjust/:id': null,
   manager:localStorage.getItem('role') === 'manager' || localStorage.getItem('role') === 'ceo' ?'/system/manager/:feature': null,
   managerAdjustCreate:localStorage.getItem('role') === 'manager' || localStorage.getItem('role') === 'ceo' ?'/system/manager/:feature/:adjust': null,
   managerAdjustUpdate:localStorage.getItem('role') === 'manager' || localStorage.getItem('role') === 'ceo' ?'/system/manager/:feature/:adjust/:id': null,
   ceo:localStorage.getItem('role') === 'ceo' ?'/system/ceo/:feature': null,
   ceoAdjustCreate:localStorage.getItem('role') === 'ceo' ?'/system/ceo/:feature/:adjust': null,
   ceoAdjustUpdate:localStorage.getItem('role') === 'ceo' ?'/system/ceo/:feature/:adjust/:id': null,
   notFound: '*',
   loginAdmin:'/system/loginAdmin',
   loginManager:'/system/loginManager',
   loginCEO:'/system/loginCEO',
   loginSeller:'/system/loginSeller'
};

export default routes;
